import type { User, Report } from '~/types';

export const testUsers: User[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 'sarah.chen@startup.io',
    tier: 'Professional',
    status: 'Active',
    joined: 'Jan 15, 2026',
    lastLogin: 'Jan 24, 2026 at 9:32 AM',
    billingCycle: 'Monthly',
    nextBillingDate: 'Feb 15, 2026',
    reportsUsed: 8,
    reportsLimit: 20,
    storageUsed: '2.4 GB',
    storageLimit: '5 GB',
    reports: [
      {
        id: 'r1',
        name: 'Q4 Sales Analysis',
        dateCreated: 'Jan 15, 2026',
        status: 'Completed',
        fileSize: '2.3 MB',
      },
      {
        id: 'r2',
        name: 'Monthly Performance Review',
        dateCreated: 'Jan 10, 2026',
        status: 'Completed',
        fileSize: '1.8 MB',
      },
      {
        id: 'r3',
        name: 'Team Productivity Report',
        dateCreated: 'Jan 5, 2026',
        status: 'Completed',
        fileSize: '3.1 MB',
      },
      {
        id: 'r4',
        name: 'Budget Forecast 2026',
        dateCreated: 'Dec 28, 2025',
        status: 'Completed',
        fileSize: '4.2 MB',
      },
      {
        id: 'r5',
        name: 'Customer Satisfaction Survey',
        dateCreated: 'Dec 20, 2025',
        status: 'Completed',
        fileSize: '1.5 MB',
      },
    ],
  },
  {
    id: '2',
    name: 'John Doe',
    email: 'john.doe@engineering.com',
    tier: 'Enterprise',
    status: 'Active',
    joined: 'Dec 28, 2025',
    lastLogin: 'Jan 24, 2026 at 11:15 AM',
    billingCycle: 'Annual',
    nextBillingDate: 'Dec 28, 2026',
    reportsUsed: 45,
    reportsLimit: 100,
    storageUsed: '12.8 GB',
    storageLimit: '50 GB',
    reports: [
      {
        id: 'r6',
        name: 'Infrastructure Analysis',
        dateCreated: 'Jan 22, 2026',
        status: 'Completed',
        fileSize: '8.5 MB',
      },
      {
        id: 'r7',
        name: 'Security Audit Report',
        dateCreated: 'Jan 18, 2026',
        status: 'Completed',
        fileSize: '6.2 MB',
      },
      {
        id: 'r8',
        name: 'Performance Metrics Q4',
        dateCreated: 'Jan 12, 2026',
        status: 'Completed',
        fileSize: '4.7 MB',
      },
      {
        id: 'r9',
        name: 'Cost Optimization Study',
        dateCreated: 'Jan 8, 2026',
        status: 'Draft',
        fileSize: '3.9 MB',
      },
      {
        id: 'r10',
        name: 'System Integration Plan',
        dateCreated: 'Jan 3, 2026',
        status: 'Completed',
        fileSize: '5.1 MB',
      },
      {
        id: 'r11',
        name: 'Cloud Migration Report',
        dateCreated: 'Dec 30, 2025',
        status: 'Completed',
        fileSize: '7.3 MB',
      },
      {
        id: 'r12',
        name: 'API Usage Analytics',
        dateCreated: 'Dec 25, 2025',
        status: 'Completed',
        fileSize: '2.8 MB',
      },
    ],
  },
  {
    id: '3',
    name: 'Emma Wilson',
    email: 'emma.wilson@enterprise.co',
    tier: 'Professional',
    status: 'Active',
    joined: 'Dec 20, 2025',
    lastLogin: 'Jan 23, 2026 at 4:45 PM',
    billingCycle: 'Monthly',
    nextBillingDate: 'Feb 20, 2026',
    reportsUsed: 15,
    reportsLimit: 20,
    storageUsed: '4.1 GB',
    storageLimit: '5 GB',
    reports: [
      {
        id: 'r13',
        name: 'Market Research Summary',
        dateCreated: 'Jan 20, 2026',
        status: 'Completed',
        fileSize: '3.2 MB',
      },
      {
        id: 'r14',
        name: 'Competitor Analysis',
        dateCreated: 'Jan 14, 2026',
        status: 'Completed',
        fileSize: '4.5 MB',
      },
      {
        id: 'r15',
        name: 'Product Roadmap Review',
        dateCreated: 'Jan 7, 2026',
        status: 'Draft',
        fileSize: '2.1 MB',
      },
    ],
  },
  {
    id: '4',
    name: 'Mike Johnson',
    email: 'mike.johnson@company.com',
    tier: 'Basic',
    status: 'Inactive',
    joined: 'Nov 12, 2025',
    lastLogin: 'Dec 15, 2025 at 2:30 PM',
    billingCycle: 'Monthly',
    nextBillingDate: 'N/A (Inactive)',
    reportsUsed: 3,
    reportsLimit: 5,
    storageUsed: '0.8 GB',
    storageLimit: '1 GB',
    reports: [
      {
        id: 'r16',
        name: 'Initial Setup Report',
        dateCreated: 'Nov 15, 2025',
        status: 'Completed',
        fileSize: '1.2 MB',
      },
      {
        id: 'r17',
        name: 'Trial Analysis',
        dateCreated: 'Nov 20, 2025',
        status: 'Draft',
        fileSize: '0.9 MB',
      },
    ],
  },
  {
    id: '5',
    name: 'Lisa Park',
    email: 'lisa.park@agency.com',
    tier: 'Enterprise',
    status: 'Active',
    joined: 'Oct 5, 2025',
    lastLogin: 'Jan 24, 2026 at 8:00 AM',
    billingCycle: 'Annual',
    nextBillingDate: 'Oct 5, 2026',
    reportsUsed: 72,
    reportsLimit: 100,
    storageUsed: '28.5 GB',
    storageLimit: '50 GB',
    reports: [
      {
        id: 'r18',
        name: 'Client Portfolio Overview',
        dateCreated: 'Jan 23, 2026',
        status: 'Completed',
        fileSize: '12.4 MB',
      },
      {
        id: 'r19',
        name: 'Campaign Performance Q4',
        dateCreated: 'Jan 19, 2026',
        status: 'Completed',
        fileSize: '8.7 MB',
      },
      {
        id: 'r20',
        name: 'Creative Assets Audit',
        dateCreated: 'Jan 15, 2026',
        status: 'Completed',
        fileSize: '15.2 MB',
      },
      {
        id: 'r21',
        name: 'Social Media Analytics',
        dateCreated: 'Jan 10, 2026',
        status: 'Completed',
        fileSize: '6.8 MB',
      },
      {
        id: 'r22',
        name: 'Brand Strategy Document',
        dateCreated: 'Jan 5, 2026',
        status: 'Completed',
        fileSize: '9.3 MB',
      },
      {
        id: 'r23',
        name: 'Market Trends 2026',
        dateCreated: 'Dec 28, 2025',
        status: 'Completed',
        fileSize: '7.1 MB',
      },
      {
        id: 'r24',
        name: 'Quarterly Business Review',
        dateCreated: 'Dec 20, 2025',
        status: 'Completed',
        fileSize: '5.6 MB',
      },
      {
        id: 'r25',
        name: 'Revenue Projections',
        dateCreated: 'Dec 15, 2025',
        status: 'Draft',
        fileSize: '4.2 MB',
      },
    ],
  },
  {
    id: '6',
    name: 'David Kim',
    email: 'david.kim@agency.com',
    tier: 'Professional',
    status: 'Active',
    joined: 'Sep 18, 2025',
    lastLogin: 'Jan 22, 2026 at 3:20 PM',
    billingCycle: 'Annual',
    nextBillingDate: 'Sep 18, 2026',
    reportsUsed: 18,
    reportsLimit: 20,
    storageUsed: '4.7 GB',
    storageLimit: '5 GB',
    reports: [
      {
        id: 'r26',
        name: 'Project Status Summary',
        dateCreated: 'Jan 21, 2026',
        status: 'Completed',
        fileSize: '2.9 MB',
      },
      {
        id: 'r27',
        name: 'Resource Allocation Plan',
        dateCreated: 'Jan 16, 2026',
        status: 'Completed',
        fileSize: '3.4 MB',
      },
      {
        id: 'r28',
        name: 'Sprint Retrospective',
        dateCreated: 'Jan 9, 2026',
        status: 'Completed',
        fileSize: '1.7 MB',
      },
    ],
  },
  {
    id: '7',
    name: 'Alex Martinez',
    email: 'alex@freelance.dev',
    tier: 'Basic',
    status: 'Active',
    joined: 'Aug 22, 2025',
    lastLogin: 'Jan 24, 2026 at 10:45 AM',
    billingCycle: 'Monthly',
    nextBillingDate: 'Feb 22, 2026',
    reportsUsed: 5,
    reportsLimit: 5,
    storageUsed: '0.95 GB',
    storageLimit: '1 GB',
    reports: [
      {
        id: 'r29',
        name: 'Freelance Income Summary',
        dateCreated: 'Jan 20, 2026',
        status: 'Completed',
        fileSize: '0.8 MB',
      },
      {
        id: 'r30',
        name: 'Client Invoice Tracker',
        dateCreated: 'Jan 12, 2026',
        status: 'Completed',
        fileSize: '0.6 MB',
      },
      {
        id: 'r31',
        name: 'Project Timeline',
        dateCreated: 'Jan 5, 2026',
        status: 'Completed',
        fileSize: '1.1 MB',
      },
      {
        id: 'r32',
        name: 'Expense Report Q4',
        dateCreated: 'Dec 28, 2025',
        status: 'Completed',
        fileSize: '0.9 MB',
      },
      {
        id: 'r33',
        name: 'Annual Tax Summary',
        dateCreated: 'Dec 20, 2025',
        status: 'Draft',
        fileSize: '1.3 MB',
      },
    ],
  },
  {
    id: '8',
    name: 'Jessica Lee',
    email: 'jessica.lee@consulting.com',
    tier: 'Professional',
    status: 'Pending',
    joined: 'Jan 20, 2026',
    lastLogin: 'Jan 20, 2026 at 5:00 PM',
    billingCycle: 'Monthly',
    nextBillingDate: 'Feb 20, 2026',
    reportsUsed: 0,
    reportsLimit: 20,
    storageUsed: '0 GB',
    storageLimit: '5 GB',
    reports: [],
  },
];
